In [10]:
import numpy as np
import math
import matplotlib.pyplot as plt

# Class 1

# Class 2

In [7]:
lam = 1
n = 10
B = np.zeros((n, n))

for i in range(n):
    for j in range(n):
        if i == 0 and j == n-1:
            B[i][j] = (-0.5)*lam
        elif i == n-1 and j == 0:
            B[i][j] = (-0.5)*lam
        elif i == j:
            B[i][j] = 1 + lam
        elif i == j-1:
            B[i][j] = (-0.5)*lam
        elif i-1 == j:
            B[i][j] = (-0.5)*lam
            
print("B:\n", B)

D = np.zeros((n, n))

for i in range(n):
    for j in range(n):
        if i == 0 and j == n-1:
            D[i][j] = (0.5)*lam
        elif i == n-1 and j == 0:
            D[i][j] = (0.5)*lam
        elif i == j:
            D[i][j] = 1 - lam
        elif i == j-1:
            D[i][j] = (0.5)*lam
        elif i-1 == j:
            D[i][j] = (0.5)*lam
            
print("D:\n", D)

B:
 [[ 2.  -0.5  0.   0.   0.   0.   0.   0.   0.  -0.5]
 [-0.5  2.  -0.5  0.   0.   0.   0.   0.   0.   0. ]
 [ 0.  -0.5  2.  -0.5  0.   0.   0.   0.   0.   0. ]
 [ 0.   0.  -0.5  2.  -0.5  0.   0.   0.   0.   0. ]
 [ 0.   0.   0.  -0.5  2.  -0.5  0.   0.   0.   0. ]
 [ 0.   0.   0.   0.  -0.5  2.  -0.5  0.   0.   0. ]
 [ 0.   0.   0.   0.   0.  -0.5  2.  -0.5  0.   0. ]
 [ 0.   0.   0.   0.   0.   0.  -0.5  2.  -0.5  0. ]
 [ 0.   0.   0.   0.   0.   0.   0.  -0.5  2.  -0.5]
 [-0.5  0.   0.   0.   0.   0.   0.   0.  -0.5  2. ]]
D:
 [[0.  0.5 0.  0.  0.  0.  0.  0.  0.  0.5]
 [0.5 0.  0.5 0.  0.  0.  0.  0.  0.  0. ]
 [0.  0.5 0.  0.5 0.  0.  0.  0.  0.  0. ]
 [0.  0.  0.5 0.  0.5 0.  0.  0.  0.  0. ]
 [0.  0.  0.  0.5 0.  0.5 0.  0.  0.  0. ]
 [0.  0.  0.  0.  0.5 0.  0.5 0.  0.  0. ]
 [0.  0.  0.  0.  0.  0.5 0.  0.5 0.  0. ]
 [0.  0.  0.  0.  0.  0.  0.5 0.  0.5 0. ]
 [0.  0.  0.  0.  0.  0.  0.  0.5 0.  0.5]
 [0.5 0.  0.  0.  0.  0.  0.  0.  0.5 0. ]]


In [11]:
u1 = np.eye(n)
u = np.eye(n)

x = B @ u1
y = D @ u

print("x:\n", x)
print("y:\n", y)

x = np.linalg.solve(x, y)
print("x:\n", x)

ans:
 [[0.  0.5 0.  0.  0.  0.  0.  0.  0.  0.5]
 [0.5 0.  0.5 0.  0.  0.  0.  0.  0.  0. ]
 [0.  0.5 0.  0.5 0.  0.  0.  0.  0.  0. ]
 [0.  0.  0.5 0.  0.5 0.  0.  0.  0.  0. ]
 [0.  0.  0.  0.5 0.  0.5 0.  0.  0.  0. ]
 [0.  0.  0.  0.  0.5 0.  0.5 0.  0.  0. ]
 [0.  0.  0.  0.  0.  0.5 0.  0.5 0.  0. ]
 [0.  0.  0.  0.  0.  0.  0.5 0.  0.5 0. ]
 [0.  0.  0.  0.  0.  0.  0.  0.5 0.  0.5]
 [0.5 0.  0.  0.  0.  0.  0.  0.  0.5 0. ]]
ans1:
 [[ 2.  -0.5  0.   0.   0.   0.   0.   0.   0.  -0.5]
 [-0.5  2.  -0.5  0.   0.   0.   0.   0.   0.   0. ]
 [ 0.  -0.5  2.  -0.5  0.   0.   0.   0.   0.   0. ]
 [ 0.   0.  -0.5  2.  -0.5  0.   0.   0.   0.   0. ]
 [ 0.   0.   0.  -0.5  2.  -0.5  0.   0.   0.   0. ]
 [ 0.   0.   0.   0.  -0.5  2.  -0.5  0.   0.   0. ]
 [ 0.   0.   0.   0.   0.  -0.5  2.  -0.5  0.   0. ]
 [ 0.   0.   0.   0.   0.   0.  -0.5  2.  -0.5  0. ]
 [ 0.   0.   0.   0.   0.   0.   0.  -0.5  2.  -0.5]
 [-0.5  0.   0.   0.   0.   0.   0.   0.  -0.5  2. ]]
x:
 [[0.15470494 0.309409

# Class 3

# Class 4